2020-05-14 00:12:01,700 - teradata.udaexec - INFO - Initializing UdaExec...
2020-05-14 00:12:01,700 - teradata.udaexec - INFO - Reading config files: ['/etc/udaexec.ini: Not Found', '/home/kamil/udaexec.ini: Not Found', '/home/kamil/Pulpit/Teradata/Repo/Teradata-statistics/udaexec.ini: Not Found']
2020-05-14 00:12:01,701 - teradata.udaexec - INFO - Found run number file: "/home/kamil/Pulpit/Teradata/Repo/Teradata-statistics/.runNumber"
2020-05-14 00:12:01,701 - teradata.udaexec - INFO - Cleaning up log files older than 90 days.
2020-05-14 00:12:01,701 - teradata.udaexec - INFO - Removed 0 log files.
2020-05-14 00:12:01,712 - teradata.udaexec - INFO - Checkpoint file not found: /home/kamil/Pulpit/Teradata/Repo/Teradata-statistics/SQL shell.checkpoint
2020-05-14 00:12:01,712 - teradata.udaexec - INFO - No previous checkpoint found, executing from beginning...
2020-05-14 00:12:01,713 - teradata.udaexec - INFO - Execution Details:
/********************************************************************************
 * Application Name: SQL shell
 *          Version: 1.0
 *       Run Number: 20200514001201-12
 *             Host: kamil-MS-7A34
 *         Platform: Linux-4.15.0-91-generic-x86_64-with-Ubuntu-18.04-bionic
 *          OS User: kamil
 *   Python Version: 3.6.9
 *  Python Compiler: GCC 8.4.0
 *     Python Build: ('default', 'Apr 18 2020 01:56:04')
 *  UdaExec Version: 15.10.0.21
 *     Program Name: script.py
 *      Working Dir: /home/kamil/Pulpit/Teradata/Repo/Teradata-statistics
 *      Git Version: git version 2.17.1
 *     Git Revision: 181db07
 *        Git Dirty: True [ M libs/analysis/daily_usage.py, M libs/samples.sql, M libs/utils.py, M script.py, M settings.json,?? .runNumber,?? logs/,?? sqls/]
 *          Log Dir: /home/kamil/Pulpit/Teradata/Repo/Teradata-statistics/logs
 *         Log File: /home/kamil/Pulpit/Teradata/Repo/Teradata-statistics/logs/SQL shell.20200514001201-12.log
 *     Config Files: ['/etc/udaexec.ini: Not Found', '/home/kamil/udaexec.ini: Not Found', '/home/kamil/Pulpit/Teradata/Repo/Teradata-statistics/udaexec.ini: Not Found']
 *      Query Bands: ApplicationName=SQL shell;Version=1.0;JobID=20200514001201-12;ClientUser=kamil;Production=False;udaAppLogFile=/home/kamil/Pulpit/Teradata/Repo/Teradata-statistics/logs/SQL shell.20200514001201-12.log;gitRevision=181db07;gitDirty=True;UtilityName=PyTd;UtilityVersion=15.10.0.21
********************************************************************************/
2020-05-14 00:12:01,713 - teradata.udaexec - INFO - Creating connection: {'method': 'odbc', 'system': '192.168.0.110', 'username': 'dbc', 'password': 'XXXXXX'}
2020-05-14 00:12:01,714 - teradata.tdodbc - INFO - Loading ODBC Library: /opt/teradata/client/ODBC_64/lib/libodbc.so
2020-05-14 00:12:01,718 - teradata.tdodbc - INFO - Available drivers: Teradata Database ODBC Driver 16.20, 
2020-05-14 00:12:01,860 - teradata.udaexec - INFO - Connection successful. Duration: 0.146 seconds. Details: {'method': 'odbc', 'system': '192.168.0.110', 'username': 'dbc', 'password': 'XXXXXX'}
2020-05-14 00:12:01,876 - teradata.udaexec - INFO - UdaExec exiting.
